### ISSUE TITLE
Overriding Direction for specific elements

### ISSUE THREAD

**Issue by usernotnull** [yassinebridi/tailwind-direction#1]
Is there a way to override an element to not change direction?
For example, let's say I have a button that scrolls to the top of the page on click, and I do not want it to have right-0 change to left-0 by the css injected from this plugin... Is there a way? I tried to override the parent div with a dir="ltr" to force it but that doesn't work obviously.

Thanks for sharing this lib!

**Comment by yassinebridi** [comment]
You would have to override the `dir` attribute to the parent element, and use both right and left elements for the targeted element like this for example:
```html
<button class="absolute right-4 left-4">Go top</button>
```

**Comment by usernotnull** [comment]
You're right, although I did try your approach as stated in my question, but the reason why it didn't work was that the element did not have a set width (relying on its child's width and margin), so when I attempted a right-0 and left-0, it went horizontal and filled the screen.
I just had to set force the dimension w-24.

Merci :)
