### ISSUE TITLE
PurgeCSS config

### ISSUE THREAD

**Issue by usernotnull** [yassinebridi/tailwind-direction#4]
Is there any recommendation on purge configuration?
Currently, when running in production mode, tailwind is purging some classes injected by this lib,
such as:

```
[dir=rtl] .right-0 {
    left: 0
}
```

The above is only found in dev mode without purging.

A temporary fix for me was to add:
```
safelist: {
    greedy: [/(right-0)|(left-0)/]
}
```

**Comment by sa3dany** [comment]
I just tested this and this was not the case, The production css contained these classes:
```js
.right-0 {
  right: 0;
}
[dir='ltr'] .right-0 {
  right: 0;
}
[dir='rtl'] .right-0 {
  left: 0;
}
```

**Comment by usernotnull** [comment]
The fix was actually easy, related to purging in general.
Since dir="ltr/rtl" is not a class, and I'm NOT writing it specifically but injecting it into the HTML such as
: ... dir="{{$localeDir}}" I had to manually write a comment in HTML as such: {{--dir="rtl"dir="ltr"--}}
Just so that purgecss reads those and skip purging them :)

**Comment by sa3dany** [comment]
Are you using tailwindcss v1?

**Comment by usernotnull** [comment]
@sa3dany no I'm on 2.0.2, the issue was with purgecss lib anyway not tailwind, resolved by actually writing dir="rtl" (or commented) and not dir="{{$dir}}" because purgecss will assume dir="rtl" is not used.

**Comment by sa3dany** [comment]
Sorry I missed your last comment. You are right, if I remove the dir
attribute from the html tag the rlt,& ltr classes are purged.
